export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SEARCH_ARTISTS_RESULT = 'SEARCH_ARTISTS_RESULT';
export const SELECT_ARTIST = 'SELECT_ARTIST';

export const GET_TRACK_LIST= 'GET_TRACK_LIST';
export const TRACK_LIST_RESULT= 'TRACK_LIST_RESULT';